[package]
name = "Flipkart-Sentiment-Analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
regex = "1.10.6"
reqwest = "0.12.5"
scraper = "0.20.0"
tokio = {version = "1.39.2", features = ["full"]}
vader_sentiment = "0.1.1"
